/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TakeawayName } from "./models/takeawayName";
export { TakeawayName } from "./models/takeawayName";
export namespace Components {
    interface AteBallApp {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TakeawayList {
        "takeawayNames": TakeawayName[];
    }
    interface TakeawayListForm {
        "takeawayNamesLength": number;
    }
}
export interface TakeawayListFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTakeawayListFormElement;
}
declare global {
    interface HTMLAteBallAppElement extends Components.AteBallApp, HTMLStencilElement {
    }
    var HTMLAteBallAppElement: {
        prototype: HTMLAteBallAppElement;
        new (): HTMLAteBallAppElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTakeawayListElement extends Components.TakeawayList, HTMLStencilElement {
    }
    var HTMLTakeawayListElement: {
        prototype: HTMLTakeawayListElement;
        new (): HTMLTakeawayListElement;
    };
    interface HTMLTakeawayListFormElement extends Components.TakeawayListForm, HTMLStencilElement {
    }
    var HTMLTakeawayListFormElement: {
        prototype: HTMLTakeawayListFormElement;
        new (): HTMLTakeawayListFormElement;
    };
    interface HTMLElementTagNameMap {
        "ate-ball-app": HTMLAteBallAppElement;
        "my-component": HTMLMyComponentElement;
        "takeaway-list": HTMLTakeawayListElement;
        "takeaway-list-form": HTMLTakeawayListFormElement;
    }
}
declare namespace LocalJSX {
    interface AteBallApp {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TakeawayList {
        "takeawayNames"?: TakeawayName[];
    }
    interface TakeawayListForm {
        "onInputChange"?: (event: TakeawayListFormCustomEvent<any>) => void;
        "onSubmit"?: (event: TakeawayListFormCustomEvent<any>) => void;
        "takeawayNamesLength"?: number;
    }
    interface IntrinsicElements {
        "ate-ball-app": AteBallApp;
        "my-component": MyComponent;
        "takeaway-list": TakeawayList;
        "takeaway-list-form": TakeawayListForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ate-ball-app": LocalJSX.AteBallApp & JSXBase.HTMLAttributes<HTMLAteBallAppElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "takeaway-list": LocalJSX.TakeawayList & JSXBase.HTMLAttributes<HTMLTakeawayListElement>;
            "takeaway-list-form": LocalJSX.TakeawayListForm & JSXBase.HTMLAttributes<HTMLTakeawayListFormElement>;
        }
    }
}
