/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TakeawayList {
        "takeawayNames": string[];
    }
}
export interface TakeawayListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTakeawayListElement;
}
declare global {
    interface HTMLTakeawayListElement extends Components.TakeawayList, HTMLStencilElement {
    }
    var HTMLTakeawayListElement: {
        prototype: HTMLTakeawayListElement;
        new (): HTMLTakeawayListElement;
    };
    interface HTMLElementTagNameMap {
        "takeaway-list": HTMLTakeawayListElement;
    }
}
declare namespace LocalJSX {
    interface TakeawayList {
        "onInputChange"?: (event: TakeawayListCustomEvent<any>) => void;
        "onSubmit"?: (event: TakeawayListCustomEvent<any>) => void;
        "onTakeawayAdded"?: (event: TakeawayListCustomEvent<any>) => void;
        "takeawayNames"?: string[];
    }
    interface IntrinsicElements {
        "takeaway-list": TakeawayList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "takeaway-list": LocalJSX.TakeawayList & JSXBase.HTMLAttributes<HTMLTakeawayListElement>;
        }
    }
}
